version: "3.4"

services:
  challenge:
    image: airhockeychallenge/challenge:latest
    build:
      context: .
      target: dev
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/tmp/.docker.xauth
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - "${PWD}/:/src/2023-challenge"
    command: bash
    network_mode: host
    working_dir: /src/2023-challenge
